apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: log-agent
  namespace: demo-app
spec:
  selector:
    matchLabels:
      app: log-agent
  template:
    metadata:
      labels:
        app: log-agent
    spec:
      containers:
      - name: log-agent
        image: busybox
        command: ["sh", "-c", "while true; do echo 'logging...'; sleep 5; done"]
