apiVersion: v1
kind: ConfigMap
metadata:
  name: my-configmap
data:
  key1: Hello, world!
  key2: |
    Test
    multiple lines
    more lines

####
# 1. create a cm
# k create cm <configmap-name>

### use configmap as an env variable
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: mynginx-deploy
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: nginx
#   template:
#     metadata:
#       labels:
#         app: nginx
#     spec:
#       containers:
#       - name: nginx
#         image: nginx:latest
#         env:
#         - name: SINGLE_VALUE
#           valueFrom:
#             configMapKeyRef:
#               name: my-configmap
#               key: key1