    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: myapp
    spec:
      replicas: 3
      selector:
        matchLabels:
          app: myapp
      template:
        metadata:
          labels:
            app: myapp
        spec:
          containers:
          - name: myapp
            image: mariahdocker123/my-app
            ports:
            - containerPort: 3000


############
# 1. Create a Deployment
# kubectl create deployment myapp --image=mariahdocker123/my-app --replicas=2 --port=3000

# 2. Scale deployment
#kubectl scale deployment myapp --replicas=2

# 3. Check deployment history and rollback to prev version
# kubectl rollout history deploy my-app

# 4. Autoscale deployment
#kubectl autoscale deployment myapp --cpu-percent=50 --min=1 --max=10
#kubectl get hpa
