services:
  web:
    image: mariahdocker123/kdcapp
    ports:
      - '3100:3000'
    volumes:
    - .:/app/code
    depends_on:
      - db
  db:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: mydatabase
      POSTGRES_USER: user
      version: '3.8'
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
